// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push_proto_common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "push_proto_common.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* ResultCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_push_5fproto_5fcommon_2eproto() {
  protobuf_AddDesc_push_5fproto_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "push_proto_common.proto");
  GOOGLE_CHECK(file != NULL);
  ResultCode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_push_5fproto_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_push_5fproto_5fcommon_2eproto() {
}

void protobuf_AddDesc_push_5fproto_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027push_proto_common.proto*]\n\nResultCode\022"
    "\022\n\016RESULT_SUCCESS\020\000\022\024\n\020RESULT_FORBIDDEN\020"
    "\001\022\023\n\017RESULT_CONFLICT\020\002\022\020\n\013RESULT_FAIL\020\220N", 120);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "push_proto_common.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_push_5fproto_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_push_5fproto_5fcommon_2eproto {
  StaticDescriptorInitializer_push_5fproto_5fcommon_2eproto() {
    protobuf_AddDesc_push_5fproto_5fcommon_2eproto();
  }
} static_descriptor_initializer_push_5fproto_5fcommon_2eproto_;
const ::google::protobuf::EnumDescriptor* ResultCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ResultCode_descriptor_;
}
bool ResultCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 10000:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
